import type { Metadata } from "next";
import "./globals.css";
import { ChakraClientProvider } from "./providers/ChakraClientProvider";
import { Container } from "@chakra-ui/react";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ChakraClientProvider>
          <Container height={"100vh"} maxW={"100vh"}>
            {children}
          </Container>
        </ChakraClientProvider>
      </body>
    </html>
  );
}
