name: Run Lint and Types Check on PR

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js and Yarn
      uses: actions/setup-node@v3
      with:
        node-version: 'current' 
        registry-url: 'https://registry.yarnpkg.com/'  # Specify Yarn registry

    - name: Install Yarn
      run: npm install -g yarn

    - name: Install dependencies with Yarn
      run: yarn install

    - name: Lint Check
      run: yarn lint

    - name: Typescript Check
      run: yarn typecheck