name: Vercel Deployment

on:
  pull_request:
    branches:
        - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 'current'
      - run: npm install -g yarn@latest

      - name: Install Dependencies
        run: yarn install

      - name: Install Vercel CLI
        run: npm install --global vercel@canary

      - name: Pull environment
        run: vercel pull --yes

      - name: Build Project Artifacts
        run: vercel build --prod

    

env:
 VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
 ORG_ID: ${{ secrets.ORG_ID }}
 PROJECT_ID: ${{ secrets.PROJECT_ID }}