name: Tests Check on PR

on:
  pull_request:
    branches:
      - main

jobs:
  Rules-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js and Yarn
      uses: actions/setup-node@v3
      with:
        node-version: 'current' 
        registry-url: 'https://registry.yarnpkg.com/'  # Specify Yarn registry

    - name: Install Yarn
      run: npm install -g yarn
    
    - name: Remove Yarn Lock
      run: |
        # rm yarn.lock f
    
    - name: Install dependencies with Yarn
      run: yarn install

    - name: Run tests
      run: yarn test
